### ISSUE TITLE
Sudden issue with the form blueprint

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#127]
Suddenly, I can't open anymore the Submissions data from the form I defined for a website.

```
Column not found: 1054 Unknown column 'nest_depth' in 'field list' in
```

complete trace i will re-post in the community forum

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nest_depth' in 'field list' in /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414
Stack trace:
#0 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): PDO->prepare()
#1 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#3 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\Database\Connection->run()
#4 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2705): Illuminate\Database\Connection->select()
#5 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\Database\Query\Builder->runSelect()
#6 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2693): Illuminate\Database\Query\Builder->onceWithColumns()
#8 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Database/QueryBuilder.php(90): Illuminate\Database\Query\Builder->get()
#9 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(710): October\Rain\Database\QueryBuilder->get()
#10 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(694): Illuminate\Database\Eloquent\Builder->getModels()
#11 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Database/Traits/NestedTree.php(524): Illuminate\Database\Eloquent\Builder->get()
#12 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1312): Tailor\Models\EntryRecord->scopeListsNested()
#13 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Database/Builder.php(227): Illuminate\Database\Eloquent\Builder->callScope()
#14 /var/www/christophevidal.co/public_html/modules/backend/formwidgets/Relation.php(230): October\Rain\Database\Builder->__call()
#15 /var/www/christophevidal.co/public_html/modules/backend/formwidgets/Relation.php(123): Backend\FormWidgets\Relation->makeRenderFormField()
#16 /var/www/christophevidal.co/public_html/modules/backend/formwidgets/Relation.php(113): Backend\FormWidgets\Relation->prepareVars()
#17 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_field_widget.php(5): Backend\FormWidgets\Relation->render()
#18 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#19 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#20 /var/www/christophevidal.co/public_html/modules/backend/widgets/Form.php(307): Backend\Classes\WidgetBase->makePartial()
#21 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_field.php(25): Backend\Widgets\Form->renderFieldElement()
#22 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#23 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#24 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_field-container.php(9): Backend\Classes\WidgetBase->makePartial()
#25 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#26 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#27 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_form_fields.php(11): Backend\Classes\WidgetBase->makePartial()
#28 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#29 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#30 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_form_tabs.php(53): Backend\Classes\WidgetBase->makePartial()
#31 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#32 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#33 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_section.php(27): Backend\Classes\WidgetBase->makePartial()
#34 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#35 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#36 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_section-container.php(13): Backend\Classes\WidgetBase->makePartial()
#37 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#38 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#39 /var/www/christophevidal.co/public_html/modules/backend/widgets/Form.php(233): Backend\Classes\WidgetBase->makePartial()
#40 /var/www/christophevidal.co/public_html/modules/backend/behaviors/FormController.php(430): Backend\Widgets\Form->render()
#41 [internal function]: Backend\Behaviors\FormController->formRender()
#42 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Extension/ExtendableTrait.php(504): call_user_func_array()
#43 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Extension/Extendable.php(55): October\Rain\Extension\Extendable->extendableCall()
#44 /var/www/christophevidal.co/public_html/modules/tailor/controllers/entries/_primary_tabs.php(2): October\Rain\Extension\Extendable->__call()
#45 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#46 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\Controller->makeFileContents()
#47 /var/www/christophevidal.co/public_html/modules/tailor/controllers/entries/_edit.php(52): Backend\Classes\Controller->makePartial()
#48 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#49 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\Controller->makeFileContents()
#50 /var/www/christophevidal.co/public_html/modules/tailor/controllers/entries/update.php(1): Backend\Classes\Controller->makePartial()
#51 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#52 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(112): Backend\Classes\Controller->makeFileContents()
#53 /var/www/christophevidal.co/public_html/modules/backend/classes/Controller.php(401): Backend\Classes\Controller->makeView()
#54 /var/www/christophevidal.co/public_html/modules/backend/classes/Controller.php(269): Backend\Classes\Controller->execPageAction()
#55 /var/www/christophevidal.co/public_html/modules/backend/classes/WildcardController.php(20): Backend\Classes\Controller->run()
#56 /var/www/christophevidal.co/public_html/modules/backend/classes/BackendController.php(98): Backend\Classes\WildcardController->run()
#57 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Backend\Classes\BackendController->run()
#58 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#59 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#60 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#61 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#62 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#63 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#65 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#66 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#67 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#68 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#69 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#70 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#71 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#72 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#73 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#74 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#75 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\Pipeline\Pipeline->then()
#76 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack()
#77 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute()
#78 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Router/CoreRouter.php(32): Illuminate\Routing\Router->dispatchToRoute()
#79 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): October\Rain\Router\CoreRouter->dispatch()
#80 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#81 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#82 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#83 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#84 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#85 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#86 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#87 /var/www/christophevidal.co/public_html/index.php(69): Illuminate\Foundation\Http\Kernel->handle()
#88 {main}
Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nest_depth' in 'field list' (SQL: select `nest_depth`, `parent_id`, `id`, `title`, `site_root_id` from `xc_f04b58ea6d8011edaa98d348ccf890efc` where `xc_f04b58ea6d8011edaa98d348ccf890efc`.`draft_mode` = 1 and `xc_f04b58ea6d8011edaa98d348ccf890efc`.`is_version` = 0 and `xc_f04b58ea6d8011edaa98d348ccf890efc`.`site_id` = 1 and `xc_f04b58ea6d8011edaa98d348ccf890efc`.`deleted_at` is null order by `nest_left` asc) in /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
Stack trace:
#0 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#1 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\Database\Connection->run()
#2 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2705): Illuminate\Database\Connection->select()
#3 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\Database\Query\Builder->runSelect()
#4 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2693): Illuminate\Database\Query\Builder->onceWithColumns()
#6 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Database/QueryBuilder.php(90): Illuminate\Database\Query\Builder->get()
#7 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(710): October\Rain\Database\QueryBuilder->get()
#8 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(694): Illuminate\Database\Eloquent\Builder->getModels()
#9 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Database/Traits/NestedTree.php(524): Illuminate\Database\Eloquent\Builder->get()
#10 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1312): Tailor\Models\EntryRecord->scopeListsNested()
#11 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Database/Builder.php(227): Illuminate\Database\Eloquent\Builder->callScope()
#12 /var/www/christophevidal.co/public_html/modules/backend/formwidgets/Relation.php(230): October\Rain\Database\Builder->__call()
#13 /var/www/christophevidal.co/public_html/modules/backend/formwidgets/Relation.php(123): Backend\FormWidgets\Relation->makeRenderFormField()
#14 /var/www/christophevidal.co/public_html/modules/backend/formwidgets/Relation.php(113): Backend\FormWidgets\Relation->prepareVars()
#15 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_field_widget.php(5): Backend\FormWidgets\Relation->render()
#16 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#17 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#18 /var/www/christophevidal.co/public_html/modules/backend/widgets/Form.php(307): Backend\Classes\WidgetBase->makePartial()
#19 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_field.php(25): Backend\Widgets\Form->renderFieldElement()
#20 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#21 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#22 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_field-container.php(9): Backend\Classes\WidgetBase->makePartial()
#23 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#24 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#25 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_form_fields.php(11): Backend\Classes\WidgetBase->makePartial()
#26 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#27 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#28 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_form_tabs.php(53): Backend\Classes\WidgetBase->makePartial()
#29 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#30 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#31 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_section.php(27): Backend\Classes\WidgetBase->makePartial()
#32 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#33 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#34 /var/www/christophevidal.co/public_html/modules/backend/widgets/form/partials/_section-container.php(13): Backend\Classes\WidgetBase->makePartial()
#35 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#36 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents()
#37 /var/www/christophevidal.co/public_html/modules/backend/widgets/Form.php(233): Backend\Classes\WidgetBase->makePartial()
#38 /var/www/christophevidal.co/public_html/modules/backend/behaviors/FormController.php(430): Backend\Widgets\Form->render()
#39 [internal function]: Backend\Behaviors\FormController->formRender()
#40 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Extension/ExtendableTrait.php(504): call_user_func_array()
#41 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Extension/Extendable.php(55): October\Rain\Extension\Extendable->extendableCall()
#42 /var/www/christophevidal.co/public_html/modules/tailor/controllers/entries/_primary_tabs.php(2): October\Rain\Extension\Extendable->__call()
#43 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#44 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\Controller->makeFileContents()
#45 /var/www/christophevidal.co/public_html/modules/tailor/controllers/entries/_edit.php(52): Backend\Classes\Controller->makePartial()
#46 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#47 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(98): Backend\Classes\Controller->makeFileContents()
#48 /var/www/christophevidal.co/public_html/modules/tailor/controllers/entries/update.php(1): Backend\Classes\Controller->makePartial()
#49 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(267): include('...')
#50 /var/www/christophevidal.co/public_html/modules/system/traits/ViewMaker.php(112): Backend\Classes\Controller->makeFileContents()
#51 /var/www/christophevidal.co/public_html/modules/backend/classes/Controller.php(401): Backend\Classes\Controller->makeView()
#52 /var/www/christophevidal.co/public_html/modules/backend/classes/Controller.php(269): Backend\Classes\Controller->execPageAction()
#53 /var/www/christophevidal.co/public_html/modules/backend/classes/WildcardController.php(20): Backend\Classes\Controller->run()
#54 /var/www/christophevidal.co/public_html/modules/backend/classes/BackendController.php(98): Backend\Classes\WildcardController->run()
#55 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Backend\Classes\BackendController->run()
#56 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#57 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#58 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#59 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#60 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#61 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#63 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#65 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#66 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#67 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#68 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#69 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#70 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#71 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#72 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#73 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\Pipeline\Pipeline->then()
#74 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack()
#75 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute()
#76 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Router/CoreRouter.php(32): Illuminate\Routing\Router->dispatchToRoute()
#77 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): October\Rain\Router\CoreRouter->dispatch()
#78 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#79 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#80 /var/www/christophevidal.co/public_html/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#81 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#82 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#83 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#84 /var/www/christophevidal.co/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#85 /var/www/christophevidal.co/public_html/index.php(69): Illuminate\Foundation\Http\Kernel->handle()
```

**Comment by artistro08** [comment]
I saw that there was a fix for this on the forum. Have you tried it yet?

**Comment by chrisvidal** [comment]
i tried the ones provided by daft (by changing to the entry to structure) but its not working in this case.

**Comment by artistro08** [comment]
Did you change it on the main yaml file or the mixin?

**Comment by chrisvidal** [comment]
it works if I change it on the `forms/forms.yaml`, from `stream` to `structure`

**Comment by artistro08** [comment]
Awesome. Glad it does
